
services:
  backend:
    build:
      context: ./prueba_back
      dockerfile: Dockerfile
    ports: 
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app/back
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - SECRET_JWT=${SECRET_JWT}
      - URL_MONGO_SERVER=${URL_MONGO_SERVER}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./prueba_front
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend:/usr/src/app/front
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
